/* ==========================================================================
   Country Quiz - dataset
   74 countries with ISO alpha-2 code, capital city and currency.
   Exposed as a global so app.js can read it without a build step.
   ========================================================================== */

var COUNTRIES = [
  { name: 'Japan',                     code: 'jp', capital: 'Tokyo',          currency: 'Japanese yen' },
  { name: 'France',                    code: 'fr', capital: 'Paris',          currency: 'Euro' },
  { name: 'Germany',                   code: 'de', capital: 'Berlin',         currency: 'Euro' },
  { name: 'Italy',                     code: 'it', capital: 'Rome',           currency: 'Euro' },
  { name: 'Spain',                     code: 'es', capital: 'Madrid',         currency: 'Euro' },
  { name: 'Portugal',                  code: 'pt', capital: 'Lisbon',         currency: 'Euro' },
  { name: 'United Kingdom',            code: 'gb', capital: 'London',         currency: 'Pound sterling' },
  { name: 'Ireland',                   code: 'ie', capital: 'Dublin',         currency: 'Euro' },
  { name: 'Netherlands',               code: 'nl', capital: 'Amsterdam',      currency: 'Euro' },
  { name: 'Belgium',                   code: 'be', capital: 'Brussels',       currency: 'Euro' },
  { name: 'Switzerland',               code: 'ch', capital: 'Bern',           currency: 'Swiss franc' },
  { name: 'Austria',                   code: 'at', capital: 'Vienna',         currency: 'Euro' },
  { name: 'Sweden',                    code: 'se', capital: 'Stockholm',      currency: 'Swedish krona' },
  { name: 'Norway',                    code: 'no', capital: 'Oslo',           currency: 'Norwegian krone' },
  { name: 'Denmark',                   code: 'dk', capital: 'Copenhagen',     currency: 'Danish krone' },
  { name: 'Finland',                   code: 'fi', capital: 'Helsinki',       currency: 'Euro' },
  { name: 'Poland',                    code: 'pl', capital: 'Warsaw',         currency: 'Polish zloty' },
  { name: 'Czech Republic',            code: 'cz', capital: 'Prague',         currency: 'Czech koruna' },
  { name: 'Hungary',                   code: 'hu', capital: 'Budapest',       currency: 'Hungarian forint' },
  { name: 'Greece',                    code: 'gr', capital: 'Athens',         currency: 'Euro' },
  { name: 'Turkey',                    code: 'tr', capital: 'Ankara',         currency: 'Turkish lira' },
  { name: 'Russia',                    code: 'ru', capital: 'Moscow',         currency: 'Russian ruble' },
  { name: 'Ukraine',                   code: 'ua', capital: 'Kyiv',           currency: 'Ukrainian hryvnia' },
  { name: 'Iceland',                   code: 'is', capital: 'Reykjavik',      currency: 'Icelandic krona' },
  { name: 'Croatia',                   code: 'hr', capital: 'Zagreb',         currency: 'Euro' },
  { name: 'Romania',                   code: 'ro', capital: 'Bucharest',      currency: 'Romanian leu' },
  { name: 'Bulgaria',                  code: 'bg', capital: 'Sofia',          currency: 'Bulgarian lev' },
  { name: 'Serbia',                    code: 'rs', capital: 'Belgrade',       currency: 'Serbian dinar' },
  { name: 'Slovakia',                  code: 'sk', capital: 'Bratislava',     currency: 'Euro' },
  { name: 'Slovenia',                  code: 'si', capital: 'Ljubljana',      currency: 'Euro' },

  { name: 'United States',             code: 'us', capital: 'Washington, D.C.', currency: 'US dollar' },
  { name: 'Canada',                    code: 'ca', capital: 'Ottawa',         currency: 'Canadian dollar' },
  { name: 'Mexico',                    code: 'mx', capital: 'Mexico City',    currency: 'Mexican peso' },
  { name: 'Cuba',                      code: 'cu', capital: 'Havana',         currency: 'Cuban peso' },
  { name: 'Jamaica',                   code: 'jm', capital: 'Kingston',       currency: 'Jamaican dollar' },

  { name: 'Brazil',                    code: 'br', capital: 'Brasilia',       currency: 'Brazilian real' },
  { name: 'Argentina',                 code: 'ar', capital: 'Buenos Aires',   currency: 'Argentine peso' },
  { name: 'Chile',                     code: 'cl', capital: 'Santiago',       currency: 'Chilean peso' },
  { name: 'Peru',                      code: 'pe', capital: 'Lima',           currency: 'Peruvian sol' },
  { name: 'Colombia',                  code: 'co', capital: 'Bogota',         currency: 'Colombian peso' },
  { name: 'Venezuela',                 code: 've', capital: 'Caracas',        currency: 'Venezuelan bolivar' },
  { name: 'Ecuador',                   code: 'ec', capital: 'Quito',          currency: 'US dollar' },

  { name: 'China',                     code: 'cn', capital: 'Beijing',        currency: 'Chinese yuan' },
  { name: 'India',                     code: 'in', capital: 'New Delhi',      currency: 'Indian rupee' },
  { name: 'Pakistan',                  code: 'pk', capital: 'Islamabad',      currency: 'Pakistani rupee' },
  { name: 'Bangladesh',                code: 'bd', capital: 'Dhaka',          currency: 'Bangladeshi taka' },
  { name: 'Sri Lanka',                 code: 'lk', capital: 'Colombo',        currency: 'Sri Lankan rupee' },
  { name: 'Nepal',                     code: 'np', capital: 'Kathmandu',      currency: 'Nepalese rupee' },
  { name: 'Thailand',                  code: 'th', capital: 'Bangkok',        currency: 'Thai baht' },
  { name: 'Vietnam',                   code: 'vn', capital: 'Hanoi',          currency: 'Vietnamese dong' },
  { name: 'Malaysia',                  code: 'my', capital: 'Kuala Lumpur',   currency: 'Malaysian ringgit' },
  { name: 'Singapore',                 code: 'sg', capital: 'Singapore',      currency: 'Singapore dollar' },
  { name: 'Indonesia',                 code: 'id', capital: 'Jakarta',        currency: 'Indonesian rupiah' },
  { name: 'Philippines',               code: 'ph', capital: 'Manila',         currency: 'Philippine peso' },
  { name: 'South Korea',               code: 'kr', capital: 'Seoul',          currency: 'South Korean won' },
  { name: 'North Korea',               code: 'kp', capital: 'Pyongyang',      currency: 'North Korean won' },
  { name: 'Mongolia',                  code: 'mn', capital: 'Ulaanbaatar',    currency: 'Mongolian tugrik' },
  { name: 'Kazakhstan',                code: 'kz', capital: 'Astana',         currency: 'Kazakhstani tenge' },

  { name: 'Saudi Arabia',              code: 'sa', capital: 'Riyadh',         currency: 'Saudi riyal' },
  { name: 'United Arab Emirates',      code: 'ae', capital: 'Abu Dhabi',      currency: 'UAE dirham' },
  { name: 'Qatar',                     code: 'qa', capital: 'Doha',           currency: 'Qatari riyal' },
  { name: 'Israel',                    code: 'il', capital: 'Jerusalem',      currency: 'Israeli new shekel' },
  { name: 'Iran',                      code: 'ir', capital: 'Tehran',         currency: 'Iranian rial' },
  { name: 'Iraq',                      code: 'iq', capital: 'Baghdad',        currency: 'Iraqi dinar' },

  { name: 'Egypt',                     code: 'eg', capital: 'Cairo',          currency: 'Egyptian pound' },
  { name: 'Morocco',                   code: 'ma', capital: 'Rabat',          currency: 'Moroccan dirham' },
  { name: 'Nigeria',                   code: 'ng', capital: 'Abuja',          currency: 'Nigerian naira' },
  { name: 'Kenya',                     code: 'ke', capital: 'Nairobi',        currency: 'Kenyan shilling' },
  { name: 'Ethiopia',                  code: 'et', capital: 'Addis Ababa',    currency: 'Ethiopian birr' },
  { name: 'Ghana',                     code: 'gh', capital: 'Accra',          currency: 'Ghanaian cedi' },
  { name: 'South Africa',              code: 'za', capital: 'Pretoria',       currency: 'South African rand' },

  { name: 'Australia',                 code: 'au', capital: 'Canberra',       currency: 'Australian dollar' },
  { name: 'New Zealand',               code: 'nz', capital: 'Wellington',     currency: 'New Zealand dollar' },
  { name: 'Fiji',                      code: 'fj', capital: 'Suva',           currency: 'Fijian dollar' }
];
