spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://shubhamtirpude20_db_user:Shubham2023@cluster0.ikif9rc.mongodb.net}
      database: journaldb
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /journal