#!/usr/bin/env python3
"""
Root Cause Analysis (RCA) Engine for CI/CD test failures
"""
import os
import sys
import json
import argparse
from pathlib import Path
import requests

class RCAEngine:
    def __init__(self, provider="openai"):
        self.provider = provider
        self.api_key = os.getenv("OPENAI_API_KEY")
    
    def parse_logs(self, log_dir):
        log_path = Path(log_dir)
        parsed = {
            "stack_traces": [],
            "console_logs": [],
            "test_results": {},
            "environment": {}
        }
        results_file = log_path / "results.json"
        if results_file.exists():
            with open(results_file) as f:
                data = json.load(f)
                parsed["test_results"] = data
        return parsed
    
    def classify_failure(self, logs):
        text = str(logs).lower()
        flake_indicators = ["timeout", "network", "connection", "unavailable", "retry", "flaky", "intermittent"]
        for indicator in flake_indicators:
            if indicator in text:
                return "Env Flake"
        return "App Bug"
    
    def analyze_with_llm(self, logs):
        prompt = self._build_prompt(logs)
        if self.provider == "openai":
            return self._call_openai(prompt)
        elif self.provider == "ollama":
            return self._call_ollama(prompt)
        else:
            raise ValueError(f"Unsupported provider: {self.provider}")
    
    def _build_prompt(self, logs):
        return f"""You are a senior QA engineer performing Root Cause Analysis on a test failure.

Test Results:
{json.dumps(logs.get('test_results', {}), indent=2)[:2000]}

Stack Traces:
{chr(10).join(logs.get('stack_traces', ['No stack traces captured']))[:3000]}

Console Logs:
{json.dumps(logs.get('console_logs', []), indent=2)[:2000]}

Please analyze and provide:
1. **Root Cause Summary** (1-2 sentences)
2. **Classification**: "Env Flake" or "App Bug"
3. **Detailed Analysis** (what specifically failed and why)
4. **Fix Recommendation** (actionable steps)
5. **Confidence Score** (0-100%)

Format as Markdown.
"""
    
    def _call_openai(self, prompt):
        response = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json"
            },
            json={
                "model": "gpt-4",
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.3,
                "max_tokens": 1000
            },
            timeout=30
        )
        response.raise_for_status()
        data = response.json()
        return data["choices"][0]["message"]["content"]
    
    def _call_ollama(self, prompt):
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": os.getenv("OLLAMA_MODEL", "llama3"),
                "prompt": prompt,
                "stream": False
            },
            timeout=60
        )
        response.raise_for_status()
        data = response.json()
        return data["response"]
    
    def generate_report(self, logs, analysis):
        classification = self.classify_failure(logs)
        report = f"""## 🔍 Root Cause Analysis Report

### Classification: **{classification}**

### Analysis
{analysis}

---
*Generated by AION RCA Engine using {self.provider}*
*Timestamp: {__import__('datetime').datetime.now().isoformat()}*
"""
        return report

def main():
    parser = argparse.ArgumentParser(description="RCA Engine")
    parser.add_argument("--log-dir", required=True)
    parser.add_argument("--output", default="rca-summary.md")
    parser.add_argument("--provider", default="openai", choices=["openai", "ollama"])
    args = parser.parse_args()
    
    engine = RCAEngine(provider=args.provider)
    logs = engine.parse_logs(args.log_dir)
    try:
        analysis = engine.analyze_with_llm(logs)
    except Exception as e:
        analysis = f"⚠️ LLM analysis failed: {str(e)}"
    report = engine.generate_report(logs, analysis)
    with open(args.output, "w") as f:
        f.write(report)
    print(report)

if __name__ == "__main__":
    main()
